const express = require('express');
const app = express();

const cors = require('cors');
app.use(cors());
app.use(express.json());

const mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1:27017/myDatabase');

const db = mongoose.connection;
// Upon connection failure
db.on('error', console.error.bind(console, 'Connection error:'));
// Upon opening the database successfully

db.once('open', function () {
  console.log("Connection is open...")
  //We have User and Admin database
  const UserSchema = mongoose.Schema({
    UserName: {
      type: String,
      required: [true, "Username is required"],
    },
    PassWord: {
      type: String,
      required: true,
    },
    favourite_locations: {
      type: Array,
      required: false,
    },
    Current_login: {
      type: Boolean,
      required: true,
    },
  });
  const AdminSchema = mongoose.Schema({
    UserName: {
      type: String,
      required: [true, "Username is required"],
    },
    PassWord: {
      type: String,
      required: true,
    },
  });

  const LocationSchema = mongoose.Schema({
    locId: {
      type: Number,
      required: true,
      unique: true,
    },
    name: {
      type: String,
      required: true,
    },
    latitude: {
      type: Number,
      required: true,
    },
    longitude: {
      type: Number,
      required: true,
    },
  });

  const EventSchema = mongoose.Schema({
    eventId: {
      type: Number,
      required: true,
      unique: true,
    },
    title: {
      type: String,
      required: true,
    },
    location: {
      type: Schema.Types.ObjectId, ref: 'Location',
      required: true,
    },
    dateTime: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    presenter: {
      type: String,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
  });

  const User = mongoose.model("User", UserSchema);
  const Admin = mongoose.model("Admin", AdminSchema);
  const Location = mongoose.model("Location", LocationSchema);
  const Event = mongoose.model("Event", EventSchema);

  app.get("/locations", (req, res) => {
    Location.find({})
      .sort({ events: -1 }) // sort by the number of events in descending order
      .then((locations) => {
        res.json(locations);
      })
      .catch((error) => {
        console.error(error);
        res.status(500).send("Error occurred while fetching locations");
      });
  });

  //load current
  app.get("/load", (req, res) => {

    User.find({ Current_login: { $eq: "true" } })
      .then((data) => {
        if (data.length == 1) {
          return res.send('Valid**user**' + data[0].UserName);
        }
      })
      .catch((error) => console.log(error));

    Admin.find({ Current_login: { $eq: "true" } })
      .then((data) => {
        if (data.length == 1) {
          return res.send('Valid**admin**' + data[0].UserName);
        }
      }
      )
      .catch((error) => {
        console.log(error)
      });

  });


  //Sign-up
  app.get("/signup", (req, res) => {

    const user_name = req.query.username;
    const pass_word = req.query.password;

    let newUser = new User({
      UserName: user_name,
      PassWord: pass_word,
      Current_login: false,
      favourite_locations: []
    });


    //Firstly,to check whether usename is used,if not used,create a new User's data in database.
    User.find({ UserName: { $eq: user_name } })
      .then((data) => {
        if (data.length == 0) {
          console.log(data.length);

          newUser
            .save()
            .then(() => {
              console.log("a new user account created successfully");
              res.setHeader('Content-Type', 'text/html');
              message = `
            <html>
              <head>
                <title>sign_information</title>
              </head>
              <body>
                <h1> Sign up successfully! this page is generated by the server </h1>
                  <p> Below is the sign up information for you </p>
                  <p>Login ID: ${user_name}</p>
                  <p>Return you to login page</p>
              </body>
              <script>
              const redir= setTimeout(()=>{window.location.replace("/login")},3000) ;
            </script> 
            </html>
              `;
              res.send(message);
            })
            .catch((error) => {
              console.log("failed to save new user account");
              message = `
          <html> 
            <head>
              <title> fail_information</title>
            </head>
            <body>
              <h1> Sign up Failed! <h1> 
              <h1>Missing input</h1>
              <h2>this page is generated by the server </h2>
              <p>Return you to sign up page</p>

            </body>
            <script>
              const redir= setTimeout(()=>{window.location.replace("/signup")},3000) ;
            </script> 
          </html>
            `;
              res.send(message);

            });
        } else {
          console.log(data.length);
          console.log("Username is used!");
          message = `
        <html>
          <head>
            <title>fail_information</title>
          </head>
          <body>
            <h1> Sign up Failed! Username is used!</h1>
            <h1>Please use another username</h1>
            <h2>this page is generated by the server </h2>
            <p>Return you to sign up page</p>
  
          </body>
          <script>
              const redir= setTimeout(()=>{window.location.replace("/signup")},3000) ;
          </script> 
        </html>
          `;
          res.send(message);
        }
      })
      .catch((err) => {
        console.log("failed to read");
      });

  });


  //login
  app.get("/login", (req, res) => {
    const user_name = req.query.username;
    const pass_word = req.query.password;
    const user_type = req.query.type;

    if (user_type == 'admin') {
      Admin.find({ UserName: { $eq: user_name } })
        .then((data) => {
          if (data.length == 1) {
            Admin.find({ PassWord: { $eq: pass_word } })
              .then((data) => {
                if (data.length == 1) {
                  res.send('Success**' + user_name + "**" + user_type);
                  //Upload current_login=true
                  Admin.findOneAndUpdate(
                    { UserName: { $eq: user_name } },
                    { Current_login: "true" },
                    { New: true },
                  )
                    .then((data) => { console.log('the updated data is:', data) })
                    .catch((error) => console.log(error));
                } else {
                  res.send("Failed**Invalid password");
                }
              })
              .catch((error) => console.log(error));
          } else {
            res.send("Failed**Invalid Username");
          }
        })
        .catch((error) => console.log(error));
    } else if (user_type == 'user') {
      User.find({ UserName: { $eq: user_name } })
        .then((data) => {
          if (data.length == 1) {
            User.find({ PassWord: { $eq: pass_word } })
              .then((data) => {
                if (data.length == 1) {
                  res.send('Success**' + user_name + "**" + user_type);
                  //update
                  User.findOneAndUpdate(
                    { UserName: { $eq: user_name } },
                    { Current_login: "true" },
                    { New: true },
                  )

                    .then((data) => { console.log('the updated data is:', data) })
                    .catch((error) => console.log(error));
                } else {
                  res.send("Failed**Invalid password");
                }
              })
              .catch((error) => console.log(error));
          } else {
            res.send("Failed**Invalid Username");
          }
        })
        .catch((error) => console.log(error));
    }
  });

  //log out
  app.get("/logout", (req, res) => {
    const User_Name = req.query.username;
    const Type = req.query.type;

    User.findOneAndUpdate(
      { Current_login: { $eq: "true" } },
      { Current_login: "false" },
      { New: true },
    )
      .then((data) => {
        let msg = `
        <html>
          <head>
            <title>logout_information</title>
          </head>
          <body>
            <h1> You are logged Out!</h1>
            <h2>this page is generated by the server </h2>
   
          </body>
          <script>
              const redir= setTimeout(()=>{window.location.replace("/")},3000) ;
          </script> 
        </html>
          `
        res.send(msg);
      })
      .catch((error) => console.log(error));



  });
});

const server = app.listen(80);